import { describe, expect, it } from "vitest";

import { BlueprintRouteSetLlmResponseSchema } from "./route-schema.js";

/**
 * `route-schema.ts` 的 co-located 单测。
 *
 * 覆盖 design §4.2 约定的 9 类场景：
 * 1. 合法响应通过；
 * 2. `routes` 缺失 → 失败；
 * 3. 零条 primary → refine 失败；
 * 4. 两条 primary → refine 失败；
 * 5. `kind` 越界 → 失败；
 * 6. `riskLevel` 越界 → 失败；
 * 7. `capabilities` 为空 → 失败；
 * 8. 额外字段静默丢弃 → 通过；
 * 9. `title` 超长 → 失败（不裁剪）。
 *
 * Validates: Requirements 3.3, 3.4, 9.2
 */

type CandidatePayload = {
  id: string;
  kind: string;
  title: string;
  summary: string;
  rationale: string;
  riskLevel: string;
  costLevel: string;
  complexity: string;
  estimatedEffort: string;
  capabilities: Array<{
    id: string;
    label: string;
    purpose: string;
    kind: string;
  }>;
};

function makeCapability(
  overrides: Partial<CandidatePayload["capabilities"][number]> = {},
): CandidatePayload["capabilities"][number] {
  return {
    id: overrides.id ?? "cap-llm",
    label: overrides.label ?? "LLM reasoning",
    purpose: overrides.purpose ?? "Generate structured plan",
    kind: overrides.kind ?? "llm",
  };
}

function makeRoute(overrides: Partial<CandidatePayload> = {}): CandidatePayload {
  return {
    id: overrides.id ?? "route-primary",
    kind: overrides.kind ?? "primary",
    title: overrides.title ?? "Primary balanced route",
    summary:
      overrides.summary ??
      "Primary route that balances delivery confidence and exploration budget.",
    rationale:
      overrides.rationale ??
      "Chosen because the SPEC intake signals a balanced delivery profile.",
    riskLevel: overrides.riskLevel ?? "medium",
    costLevel: overrides.costLevel ?? "medium",
    complexity: overrides.complexity ?? "balanced",
    estimatedEffort: overrides.estimatedEffort ?? "2 days",
    capabilities: overrides.capabilities ?? [makeCapability()],
  };
}

function makeValidPayload(): {
  routes: CandidatePayload[];
  summary?: string;
} {
  return {
    routes: [
      makeRoute(),
      makeRoute({
        id: "route-alt-1",
        kind: "alternative",
        title: "Documentation-first conservative route",
        summary: "Alternative route prioritising documentation before execution.",
        rationale: "Lower risk path when intake lacks validated assets.",
        riskLevel: "low",
        costLevel: "low",
        complexity: "light",
        estimatedEffort: "1 day",
      }),
    ],
    summary: "Two candidate routes generated by the LLM planner.",
  };
}

describe("BlueprintRouteSetLlmResponseSchema", () => {
  it("accepts a well-formed response with exactly one primary route", () => {
    const payload = makeValidPayload();

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(true);
  });

  it("rejects payloads missing the routes array", () => {
    const payload = { summary: "missing routes" } as unknown;

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.message).toMatch(/routes/i);
    }
  });

  it("rejects payloads with zero primary routes", () => {
    const payload = makeValidPayload();
    payload.routes[0].kind = "alternative";
    payload.routes[0].id = "route-alt-0";

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.message).toMatch(/primary/i);
    }
  });

  it("rejects payloads with two primary routes", () => {
    const payload = makeValidPayload();
    payload.routes[1].kind = "primary";

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.message).toMatch(/primary/i);
    }
  });

  it("rejects payloads where kind is outside the allowed enum", () => {
    const payload = makeValidPayload();
    payload.routes[0].kind = "fallback";

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.message).toMatch(/kind/i);
    }
  });

  it("rejects payloads where riskLevel is outside the allowed enum", () => {
    const payload = makeValidPayload();
    payload.routes[0].riskLevel = "critical";

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.message).toMatch(/riskLevel/i);
    }
  });

  it("rejects payloads with empty capabilities arrays", () => {
    const payload = makeValidPayload();
    payload.routes[0].capabilities = [];

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.message).toMatch(/capabilities/i);
    }
  });

  it("silently strips unknown top-level and route-level fields", () => {
    const payload = {
      ...makeValidPayload(),
      unknownTopLevel: "ignored",
      routes: [
        { ...makeRoute(), extraRouteField: "ignored" },
        {
          ...makeRoute({
            id: "route-alt-1",
            kind: "alternative",
            title: "Alt route",
          }),
          anotherUnknown: 42,
        },
      ],
    } as unknown;

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.routes).toHaveLength(2);
      expect(
        (result.data.routes[0] as Record<string, unknown>).extraRouteField,
      ).toBeUndefined();
      expect(
        (result.data as Record<string, unknown>).unknownTopLevel,
      ).toBeUndefined();
    }
  });

  it("rejects payloads whose title exceeds the 120-character cap (no truncation)", () => {
    const payload = makeValidPayload();
    const overLongTitle = "a".repeat(121);
    payload.routes[0].title = overLongTitle;

    const result = BlueprintRouteSetLlmResponseSchema.safeParse(payload);

    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.message).toMatch(/title/i);
      // The schema must reject rather than quietly truncate the title.
      expect(payload.routes[0].title).toHaveLength(121);
    }
  });
});
