import { latestTrustedReport } from "@shared/blueprint/whybuddy-delivery-chain";
import { replayCoverage } from "@shared/blueprint/whybuddy-coverage-replay";
import type { V5SessionState } from "@shared/blueprint/v5-reasoning-state";
import { deriveTrustSeal } from "./derive-trust-seal";
import { parseReportSections } from "./parse-report-sections";

/** Pure md serializer for Knife C delivery export — does not mutate state. */
export function serializeWhyBuddyDeliveryMd(state: V5SessionState): string {
  const report = latestTrustedReport(state);
  const seal = deriveTrustSeal(state);
  const replay = replayCoverage(state);
  const lines: string[] = [];

  lines.push("# WhyBuddy 交付包");
  lines.push("");
  lines.push(`> ${seal.displayLine}`);
  lines.push("");
  lines.push(`**目标**: ${state.goal?.text || "—"}`);
  lines.push(`**结论状态**: ${state.goal?.status || "—"}`);
  lines.push(`**交付阶段**: ${state.deliveryPhase || "none"}`);
  lines.push("");

  if (report) {
    lines.push("## 报告全文");
    lines.push("");
    const sections = parseReportSections(report);
    for (const sec of sections) {
      lines.push(`### ${sec.label}`);
      lines.push("");
      lines.push(sec.body.trim() || "（空）");
      lines.push("");
      if (sec.evidenceRefs.length > 0) {
        lines.push(`证据引用: ${sec.evidenceRefs.join(", ")}`);
        lines.push("");
      }
    }
  }

  lines.push("## T_LEDGER 摘要");
  lines.push("");
  const structureRows = (state.structureGateLedger || []).slice(-12);
  if (structureRows.length === 0) {
    lines.push("（无 structure gate 记录）");
  } else {
    for (const row of structureRows) {
      lines.push(
        `- ${row.gateId} attempt=${row.attempt ?? 0} status=${row.status} turn=${row.turnId || "—"}`
      );
    }
  }
  lines.push("");
  const flowRows = (state.flowBoundaryLedger || []).slice(-12);
  if (flowRows.length > 0) {
    lines.push("### Flow boundary");
    for (const row of flowRows) {
      lines.push(
        `- ${row.id} turn=${row.turnId} passed=${row.passed} source=${row.source}`
      );
    }
    lines.push("");
  }

  lines.push("## 证据出处");
  lines.push("");
  const stale = new Set(state.staleArtifactIds || []);
  const evidenceArts = (state.artifacts || []).filter(
    (a) =>
      a.kind === "evidence" &&
      (a.trustLevel === "gated_pass" || a.trustLevel === "audited") &&
      !stale.has(a.id)
  );
  if (evidenceArts.length === 0) {
    lines.push("（无健康 evidence 产物）");
  } else {
    for (const ev of evidenceArts) {
      lines.push(
        `- **${ev.id}** · provenance=${ev.provenance || "—"} · ${(ev.summary || ev.title || "").slice(0, 120)}`
      );
    }
  }
  lines.push("");

  lines.push("## GCOV 覆盖回放");
  lines.push("");
  lines.push(`模式: ${replay.mode || "—"} · gatePassed: ${replay.gatePassed}`);
  for (const req of replay.required) {
    lines.push(
      `- ${req.capabilityId}${req.isConvergenceAction ? " (收敛)" : ""}: ${
        req.satisfied ? "✓" : "✗"
      }${req.satisfiedByArtifactId ? ` ← ${req.satisfiedByArtifactId}` : ""}`
    );
  }
  if (replay.openGapIds.length > 0) {
    lines.push("");
    lines.push(`开放缺口: ${replay.openGapIds.join(", ")}`);
  }

  lines.push("");
  lines.push("---");
  lines.push(`Generated by WhyBuddy · session=${state.sessionId || "—"}`);

  return lines.join("\n");
}

export function downloadWhyBuddyDeliveryMd(state: V5SessionState, filename?: string): void {
  const md = serializeWhyBuddyDeliveryMd(state);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download =
    filename ||
    `whybuddy-delivery-${state.sessionId || "session"}-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}