import type { DetailPayload, OverviewPayload } from './types';

export const previewOverviewPayload: OverviewPayload = {
  queueRunning: true,
  counts: {
    queueTotal: 18,
    total: 42,
    running: 1,
    done: 12,
    reviewed: 6,
    pending: 14,
    failed: 2,
  },
  current: {
    taskLabel: 'backend-python-production-takeover-104',
    phaseLabel: 'Grok 修复中',
    status: 'GROK_FIX',
    elapsedText: '18 分 32 秒',
  },
  tasks: [
    {
      id: 'backend-python-production-takeover-104',
      task: 'agent-loop/tasks/backend-python-production-takeover-104.md',
      taskLabel: 'backend-python-production-takeover-104',
      statusLabel: '运行中',
      outcomeGroup: 'running',
      running: true,
      enabled: true,
      agent: 'Grok / Codex',
      fixAgent: 'grok',
      reviewAgent: 'codex',
      branch: 'agent-loop/migration-queue',
      diffBytes: 18432,
      lastUpdatedText: '2026-06-24 14:22:18',
    },
    {
      id: 'backend-python-auth-policy-closure-104',
      task: 'agent-loop/tasks/backend-python-auth-policy-closure-104.md',
      taskLabel: 'backend-python-auth-policy-closure-104',
      statusLabel: '已审查',
      outcomeGroup: 'reviewed',
      enabled: true,
      agent: 'Grok / Codex',
      branch: 'agent-loop/migration-queue',
      diffBytes: 9216,
      lastUpdatedText: '2026-06-24 13:48:09',
    },
    {
      id: 'backend-python-web-aigc-provider-closure-104',
      task: 'agent-loop/tasks/backend-python-web-aigc-provider-closure-104.md',
      taskLabel: 'backend-python-web-aigc-provider-closure-104',
      statusLabel: '待跑',
      outcomeGroup: 'pending',
      enabled: true,
      agent: 'Grok / Codex',
      branch: 'agent-loop/migration-queue',
      lastUpdatedText: '-',
    },
  ],
};

export const previewDetailPayload: DetailPayload = {
  taskLabel: 'backend-python-production-takeover-104',
  taskPath: 'agent-loop/tasks/backend-python-production-takeover-104.md',
  runId: '2026-06-24T06-18-44-826Z',
  status: 'GROK_FIX',
  phaseLabel: 'Grok 修复中',
  elapsedText: '18 分 32 秒',
  gateText: '基线 Gate 红 (2)',
  gateOk: false,
  agentText: 'Grok / Codex',
  fixAgent: 'grok',
  reviewAgent: 'codex',
  repo: 'github.com/acme/backend-python',
  commit: '8f7g6h5',
  activeTab: 'review',
  pipelineSteps: [
    { key: 'INIT', label: '任务准入', done: true },
    { key: 'BASELINE_GATE_RESULT', label: '基线 Gate', done: true },
    { key: 'GROK_FIX', label: 'Worker', active: true },
    { key: 'POST_FIX_GATE_RESULT', label: '修复 Gate' },
    { key: 'CODEX_REVIEW', label: 'Reviewer' },
    { key: 'DONE_REVIEWED', label: '已交付' },
  ],
  iterations: [
    { iteration: 1, gateText: '基线 Gate 红 (2)', diffBytes: 12288, summary: '补齐生产接管诊断入口。' },
    { iteration: 2, gateText: '修复 Gate 红 (1)', diffBytes: 6144, summary: '收敛 provider readiness 输出。' },
  ],
  reviewRounds: [
    {
      round: 1,
      verdict: 'needs_changes',
      decision: 'needs_changes',
      riskLevel: 'medium',
      summary: '生产接管证据基本完整，但 readiness 失败分类需要更清晰。',
      findings: [
        { severity: 'medium', path: 'server/providers/readiness.py', message: '缺少 skipped 与 failed 的分层统计。' },
      ],
    },
  ],
  events: [
    { status: 'INIT', label: '初始化', timeText: '14:18:44', iteration: null },
    { status: 'WORKTREE_READY', label: 'worktree 就绪', timeText: '14:18:50', iteration: null },
    { status: 'BASELINE_GATE_RESULT', label: '基线 gate 红 (2)', timeText: '14:19:02', iteration: null },
    { status: 'GROK_FIX', label: 'Grok 修复中', timeText: '14:19:03', iteration: 1 },
    { status: 'POST_FIX_GATE_RESULT', label: '修复 gate 红 (1)', timeText: '14:31:18', iteration: 1 },
  ],
  diffText: [
    'diff --git a/server/providers/readiness.py b/server/providers/readiness.py',
    '+def classify_provider_status(status):',
    '+    if status in {"ready", "skipped", "failed"}:',
    '+        return status',
    '+    return "failed"',
  ].join('\n'),
  agentTail: JSON.stringify({
    status: 'running',
    worker: 'grok',
    latest_action: 'readiness diagnostics',
    next: 'rerun targeted gate',
  }, null, 2),
  reportPath: 'C:/repo/.agent-loop/latest/final-report.md',
  reportJsonPath: 'C:/repo/.agent-loop/latest/final-report.json',
  landingPath: 'C:/repo/.agent-loop/latest/landing.json',
  statePath: 'C:/repo/.agent-loop/latest/state.json',
  landing: { status: 'PENDING_APPLY' },
};
